### ISSUE TITLE
Please add Open Source license to this project

### ISSUE THREAD

**Issue by obscurerichard** [burukuru/jenkins-update-ec2-ami#1]
Would you consider adding a license file to this project? This would be consistent with good [community practices](http://wiki.opensource.org/bin/Projects/How+to+apply+an+open+source+license+to+your+project) and would allow others to build upon your work with a clear set of rules for what is acceptable.

For maximum compatibility with other free software projects, please consider using MIT license, such as expressed here:

https://opensource.org/licenses/MIT

(replace the copyright statement with your copyright, of course)

If I'm reading [your blog article](https://github.com/jenkinsci/ec2-plugin) correctly this may be derived in part from a [gist attached to a PR to an MIT-licensed project from @marvinpinto](https://gist.github.com/marvinpinto/a6c9b5119d418a65d489), so it would make sense to MIT-license your project, if Marvin Pinto is also agreeable (I asked him in the gist just now).

**Comment by burukuru** [comment]
Happy to MIT License this too. Seeing as most of the code is written by @marvinpinto, maybe he can do a PR with a license file with an appropriate copyright notice.

Otherwise I'm happy to do something like this:
```
Original work Copyright 2015 Marvin Pinto
Modified work Copyright 2017 Thanh C Pham 
```
